version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    logging:
      driver: awslogs
      options: 
        awslogs-region: us-east-2
        awslogs-group: my-docker-group
        awslogs-create-group: true

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-region: us-east-2
        awslogs-group: my-docker-group
        awslogs-create-group: true
